# Chesed — root Makefile
#
# Project-management / governance targets. Backend build/test/lint targets live
# in backend/Makefile; frontend targets live in frontend/package.json. This root
# Makefile is the home for cross-cutting delivery and backlog-governance targets.
#
# Single source of truth for story status is docs/09-backlog.md.
# tasks/STATUS.md is GENERATED by `make status` and must never be hand-edited.

ROOT_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
BACKLOG  := $(ROOT_DIR)docs/09-backlog.md
REQS     := $(ROOT_DIR)docs/03-requirements-catalog.md
STATUS   := $(ROOT_DIR)tasks/STATUS.md

.PHONY: status validate-backlog

## status: regenerate the story status board from the backlog into tasks/STATUS.md
status:
	@mkdir -p $(ROOT_DIR)tasks
	@bash $(ROOT_DIR)scripts/generate-status.sh $(BACKLOG) > $(STATUS)
	@echo "Wrote $(STATUS)"

## validate-backlog: assert backlog metadata integrity (status enum, depends_on
## and covers_requirements reference real IDs). Exits non-zero on any violation.
validate-backlog:
	@bash -c '\
	  set -euo pipefail; \
	  backlog="$(BACKLOG)"; reqs="$(REQS)"; \
	  errors=0; \
	  valid_status="backlog ready in_progress review blocked done"; \
	  \
	  story_ids="$$(grep -oE "S[0-9]+\.[0-9]+" "$$backlog" | sort -u)"; \
	  req_ids="$$(grep -oE "R[NF]+-[0-9]+[a-z]?" "$$reqs" | sort -u)"; \
	  \
	  while IFS= read -r line; do \
	    val="$$(printf "%s" "$$line" | sed -E "s/^[[:space:]]*-[[:space:]]*status:[[:space:]]*//")"; \
	    ok=0; \
	    for s in $$valid_status; do \
	      if [ "$$val" = "$$s" ]; then ok=1; fi; \
	    done; \
	    if [ "$$ok" -ne 1 ]; then \
	      echo "ERROR: invalid status value: \"$$val\" (allowed: $$valid_status)"; \
	      errors=$$((errors+1)); \
	    fi; \
	  done < <(grep -E "^[[:space:]]*-[[:space:]]*status:" "$$backlog"); \
	  \
	  while IFS= read -r line; do \
	    ids="$$(printf "%s" "$$line" | grep -oE "S[0-9]+\.[0-9]+" || true)"; \
	    for id in $$ids; do \
	      if ! printf "%s\n" "$$story_ids" | grep -qx "$$id"; then \
	        echo "ERROR: depends_on references unknown story: $$id"; \
	        errors=$$((errors+1)); \
	      fi; \
	    done; \
	  done < <(grep -E "^[[:space:]]*-[[:space:]]*depends_on:" "$$backlog"); \
	  \
	  while IFS= read -r line; do \
	    ids="$$(printf "%s" "$$line" | grep -oE "R[NF]+-[0-9]+[a-z]?" || true)"; \
	    for id in $$ids; do \
	      if ! printf "%s\n" "$$req_ids" | grep -qx "$$id"; then \
	        echo "ERROR: covers_requirements references unknown requirement: $$id"; \
	        errors=$$((errors+1)); \
	      fi; \
	    done; \
	  done < <(grep -E "^[[:space:]]*-[[:space:]]*covers_requirements:" "$$backlog"); \
	  \
	  if [ "$$errors" -ne 0 ]; then \
	    echo "validate-backlog: FAILED with $$errors error(s)" >&2; \
	    exit 1; \
	  fi; \
	  echo "validate-backlog: OK"; \
	'

# --- additional targets (deliver, etc.) appended by autonomy phase ---

# =============================================================================
# Autonomous delivery pipeline (`make deliver`)
# =============================================================================
#
# `make deliver` chains every LOCAL quality gate into one fail-fast command and
# ends — by design — exactly before `git push`. It NEVER runs `git push`,
# `gh pr create`, or `gh pr merge`: the GitHub PAT has no push/PR/merge
# permission. Delivery succeeds = local commits on the branch + an APPROVE
# verdict file at tasks/review-<branch>.md + a printed READY-FOR-PR banner that
# only SUGGESTS the push command for a human to run.
#
# See .project-ai/workflows/autonomous-delivery.md for the end-to-end loop
# (including the up-to-3-cycle auto-remediation) that drives this target.
#
# Step nature (be honest about what each step is):
#   real-shell : runs a command, fails the pipeline on non-zero exit.
#   docker-gated: real-shell when Docker is up; prints SKIPPED + continues when not.
#   agent-step : produced by an AI agent out-of-band; this Makefile only GATES on
#                the artifact the agent leaves behind (the verdict file / DoD).
#
# Step order:
#   1. validate-backlog        (real-shell)
#   2. tdd-gate                (best-effort warn; authoritative gate is pre-review.md)
#   3. backend gates           (real-shell; test-integration is docker-gated)
#   4. frontend gates          (real-shell)
#   5. e2e smoke               (docker-gated — needs the compose stack)
#   6. critical-review-gate    (agent-step artifact: tasks/review-<branch>.md == APPROVE)
#   7. dod-gate                (agent-step checked gate: definition-of-done.md)
#   on all green -> READY-FOR-PR banner + SUGGESTED (not executed) push command.

BRANCH      := $(shell git rev-parse --abbrev-ref HEAD)
REVIEW_FILE := $(ROOT_DIR)tasks/review-$(BRANCH).md
DOD_FILE    := $(ROOT_DIR).project-ai/checklists/definition-of-done.md
BACKEND_DIR := $(ROOT_DIR)backend
FRONTEND_DIR:= $(ROOT_DIR)frontend

.PHONY: deliver deliver-tdd-gate deliver-backend deliver-frontend \
        deliver-e2e-smoke deliver-review-gate deliver-dod-gate deliver-ready

## deliver: run the full local autonomous delivery pipeline (fail-fast) and stop
## before push. On all-green, prints READY-FOR-PR and the SUGGESTED push command.
deliver: validate-backlog deliver-tdd-gate deliver-backend deliver-frontend \
         deliver-e2e-smoke deliver-review-gate deliver-dod-gate deliver-ready

## deliver-tdd-gate: best-effort TDD commit-order check (RED before GREEN).
## NOTE: this is a heuristic convenience only. The AUTHORITATIVE TDD gate is the
## pre-review hook (.project-ai/hooks/pre-review.md), which parses the full
## per-story commit history. Here we only inspect the branch's commits vs main
## and warn; we do not fail the pipeline on this heuristic alone.
deliver-tdd-gate:
	@echo "==> [2/7] TDD commit-order gate (best-effort; authoritative = pre-review.md)"
	@bash -c '\
	  set -uo pipefail; \
	  base="$$(git merge-base main HEAD 2>/dev/null || true)"; \
	  if [ -z "$$base" ]; then \
	    echo "    SKIPPED: no merge-base with main (detached or main itself); authoritative gate runs in pre-review.md"; \
	    exit 0; \
	  fi; \
	  test_re="(_test\.go|\.test\.tsx?|\.integration\.test\.tsx?|^frontend/e2e/.*\.spec\.ts)$$"; \
	  prod_re="^(backend/|frontend/src/)"; \
	  first_test=""; first_prod=""; idx=0; \
	  for sha in $$(git rev-list --reverse "$$base"..HEAD); do \
	    idx=$$((idx+1)); \
	    files="$$(git show --name-only --pretty=format: "$$sha" | grep -v "^$$" || true)"; \
	    if [ -z "$$first_test" ] && printf "%s\n" "$$files" | grep -Eq "$$test_re"; then first_test=$$idx; fi; \
	    if [ -z "$$first_prod" ]; then \
	      if printf "%s\n" "$$files" | grep -Eq "$$prod_re" \
	         && printf "%s\n" "$$files" | grep -Ev "$$test_re" | grep -Eq "$$prod_re"; then first_prod=$$idx; fi; \
	    fi; \
	  done; \
	  if [ -z "$$first_test" ] && [ -z "$$first_prod" ]; then \
	    echo "    OK: no test/production commits on this branch (nothing to order)"; \
	  elif [ -n "$$first_test" ] && { [ -z "$$first_prod" ] || [ "$$first_test" -le "$$first_prod" ]; }; then \
	    echo "    OK (heuristic): first test-touching commit precedes first production-touching commit"; \
	  else \
	    echo "    WARNING (heuristic): production commit appears before the first test commit on this branch."; \
	    echo "             This is NOT a hard failure here. The authoritative RED->GREEN gate is"; \
	    echo "             .project-ai/hooks/pre-review.md (per-story git-log parsing). Run it before PR."; \
	  fi; \
	  echo "    TODO: promote this heuristic to a hard gate once per-story scoping is scripted (mirror pre-review.md)."; \
	'

## deliver-backend: backend build + lint + unit tests (real-shell); integration
## tests are docker-gated (SKIPPED when Docker is absent, fail on real failures
## when Docker is present).
deliver-backend:
	@echo "==> [3/7] Backend gates: build + lint + test (+ test-integration if Docker)"
	@$(MAKE) -C $(BACKEND_DIR) build
	@$(MAKE) -C $(BACKEND_DIR) lint
	@$(MAKE) -C $(BACKEND_DIR) test
	@bash -c '\
	  if docker info >/dev/null 2>&1; then \
	    echo "    Docker detected -> running make test-integration (real failures DO fail the pipeline)"; \
	    $(MAKE) -C $(BACKEND_DIR) test-integration; \
	  else \
	    echo "    SKIPPED-NEEDS-DOCKER: backend test-integration (and auth_middleware_test) require Docker."; \
	    echo "                          The sprint gate REQUIRES these green; run locally with Docker up."; \
	  fi; \
	'

## deliver-frontend: frontend typecheck + lint + unit + integration + coverage +
## build (all real-shell; no Docker required).
deliver-frontend:
	@echo "==> [4/7] Frontend gates: typecheck + lint + test + test:integration + test:coverage + build"
	@cd $(FRONTEND_DIR) && npm run typecheck
	@cd $(FRONTEND_DIR) && npm run lint
	@cd $(FRONTEND_DIR) && npm run test
	@cd $(FRONTEND_DIR) && npm run test:integration
	@cd $(FRONTEND_DIR) && npm run test:coverage
	@cd $(FRONTEND_DIR) && npm run build

## deliver-e2e-smoke: Playwright smoke flow against the real compose stack.
## Docker-gated: SKIPPED-NEEDS-DOCKER when Docker is absent; fails on real
## failures when Docker is present. The sprint gate REQUIRES this green.
deliver-e2e-smoke:
	@echo "==> [5/7] E2E smoke (Playwright against the real stack)"
	@bash -c '\
	  if docker info >/dev/null 2>&1; then \
	    echo "    Docker detected -> running npm run test:e2e:smoke (real failures DO fail the pipeline)"; \
	    cd $(FRONTEND_DIR) && npm run test:e2e:smoke; \
	  else \
	    echo "    SKIPPED-NEEDS-DOCKER: E2E smoke needs the docker-compose stack (frontend + Go API + Postgres)."; \
	    echo "                          The sprint gate REQUIRES this green; run locally with Docker up."; \
	  fi; \
	'

## deliver-review-gate: GATE on the critical-review verdict file produced by the
## autonomous-critical-review skill (agent-step). FAILS if the file is missing or
## its verdict is not APPROVE. The Makefile never runs the agent; it only checks
## the artifact. See .project-ai/skills/autonomous-critical-review.md.
deliver-review-gate:
	@echo "==> [6/7] Critical-review gate (consumes $(REVIEW_FILE))"
	@bash -c '\
	  set -uo pipefail; \
	  file="$(REVIEW_FILE)"; \
	  if [ ! -f "$$file" ]; then \
	    echo "    FAIL: review verdict file not found: $$file" >&2; \
	    echo "          Produce it with the autonomous-critical-review skill (reviewer.md over git diff main...HEAD)." >&2; \
	    echo "          See .project-ai/workflows/autonomous-delivery.md." >&2; \
	    exit 1; \
	  fi; \
	  verdict="$$(grep -Eo "^###?[[:space:]]*Verdict:[[:space:]]*(APPROVE|REQUEST_CHANGES|NEEDS_DISCUSSION)[[:space:]]*$$" "$$file" | tail -1 | grep -Eo "(APPROVE|REQUEST_CHANGES|NEEDS_DISCUSSION)" || true)"; \
	  if [ "$$verdict" = "APPROVE" ]; then \
	    echo "    OK: verdict is APPROVE"; \
	  else \
	    echo "    FAIL: critical-review verdict is not APPROVE ($${verdict:-no canonical verdict heading found}) in $$file" >&2; \
	    echo "          The authoritative verdict is the LAST \"### Verdict: ...\" heading in the file." >&2; \
	    echo "          Run the auto-remediation loop (.project-ai/workflows/autonomous-delivery.md) and re-run make deliver." >&2; \
	    exit 1; \
	  fi; \
	'

## deliver-dod-gate: GATE on the Definition of Done checklist (agent-step). The
## DoD is verified by the agent per .project-ai/checklists/definition-of-done.md;
## this target confirms the checklist exists and reminds that DoD is blocking.
deliver-dod-gate:
	@echo "==> [7/7] Definition of Done gate ($(DOD_FILE))"
	@bash -c '\
	  set -uo pipefail; \
	  if [ ! -f "$(DOD_FILE)" ]; then \
	    echo "    FAIL: DoD checklist not found: $(DOD_FILE)" >&2; \
	    exit 1; \
	  fi; \
	  echo "    OK: DoD checklist present. The applicable DoD level (Story/Feature/Sprint)"; \
	  echo "        must be satisfied by the agent before READY-FOR-PR (blocking, agent-verified)."; \
	'

## deliver-ready: final all-green banner. Prints READY-FOR-PR and the SUGGESTED
## (NOT executed) push command. The pipeline STOPS here — it never pushes.
deliver-ready:
	@echo ""
	@echo "================================================================"
	@echo "  READY-FOR-PR"
	@echo "================================================================"
	@echo "  Branch                : $(BRANCH)"
	@echo "  Critical-review verdict: APPROVE ($(REVIEW_FILE))"
	@echo "  All local gates       : PASSED (Docker-gated steps may be SKIPPED above)"
	@echo ""
	@echo "  This pipeline STOPS before push by design. The agent never runs"
	@echo "  git push / gh pr create / gh pr merge. A human runs the push below:"
	@echo ""
	@echo "    ! git push -u origin $(BRANCH)"
	@echo ""
	@echo "================================================================"
