DELETE FROM service_type WHERE category IN ('LEGAL', 'MEDICAL', 'NUTRITIONAL', 'PHYSIOTHERAPY', 'SOCIAL', 'EDUCATIONAL', 'PSYCHOLOGICAL', 'OTHER');
DELETE FROM campus WHERE id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11';
