#!/usr/bin/env bash
#
# generate-status.sh — render the story status board from the backlog.
#
# Single source of truth is docs/09-backlog.md. This script parses the
# annotated Sprint 3-4 / Phase 1 stories (those carrying status/size/depends_on/
# parallel_with fields) and emits a Markdown table to stdout. It is the generator
# behind `make status` (which writes the output to tasks/STATUS.md).
#
# Never hand-edit tasks/STATUS.md — regenerate it with `make status`.
#
# Backlog story shape expected:
#   **S05.3 - Sync queue and push (drainer)**
#   - status: ready
#   - depends_on: [S05.1, S05.2]
#   - parallel_with: [S05.4]
#   - size: L
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKLOG="${1:-$ROOT_DIR/docs/09-backlog.md}"

if [ ! -f "$BACKLOG" ]; then
  echo "generate-status.sh: backlog not found: $BACKLOG" >&2
  exit 1
fi

echo "# Story Status Board"
echo
echo "> Generated by \`make status\` from docs/09-backlog.md. Do not edit by hand."
echo
echo "| Story | Status | Size | Depends | Parallel |"
echo "| --- | --- | --- | --- | --- |"

awk '
  # Match a story title line:  **S04.1 - Create triage**
  /^\*\*S[0-9]+\.[0-9]+ / {
    # flush the previous story before starting a new one
    if (story != "") { emit() }
    line = $0
    sub(/^\*\*/, "", line)
    sub(/\*\*$/, "", line)
    # story id is the leading token up to the first space
    split(line, parts, " ")
    story = parts[1]
    status = "-"; size = "-"; depends = "-"; parallel = "-"
    next
  }

  story != "" && /^- status:/    { status   = value(); next }
  story != "" && /^- size:/      { size     = value(); next }
  story != "" && /^- depends_on:/  { depends  = listval(); next }
  story != "" && /^- parallel_with:/ { parallel = listval(); next }

  END { if (story != "") emit() }

  function value(   v) {
    v = $0
    sub(/^- [a-z_]+:[ \t]*/, "", v)
    gsub(/^[ \t]+|[ \t]+$/, "", v)
    if (v == "") v = "-"
    return v
  }

  # Normalize a "[A, B]" list into "A, B" (drop brackets, keep contents).
  function listval(   v) {
    v = value()
    gsub(/^\[/, "", v)
    gsub(/\]$/, "", v)
    gsub(/^[ \t]+|[ \t]+$/, "", v)
    if (v == "") v = "-"
    return v
  }

  # Only emit stories that actually carry status metadata (annotated Sprint 3-4 /
  # Phase 1 stories). Unannotated stories (status still "-") are skipped so the
  # board shows only the slice that is tracked.
  function emit() {
    if (status != "-") {
      printf("| %s | %s | %s | %s | %s |\n", story, status, size, depends, parallel)
    }
    story = ""
  }
' "$BACKLOG"
