export interface Country {
  code: string;
  alpha2: string;
  name: string;
  phoneCode: string;
  flag: string;
}

function flag(alpha2: string): string {
  return String.fromCodePoint(
    ...alpha2.split('').map((c) => 0x1f1e6 + c.charCodeAt(0) - 65),
  );
}

/**
 * Comprehensive country list (ISO 3166-1).
 * Names in Portuguese (Brazilian). Sorted alphabetically with Brasil first.
 */
export const COUNTRIES: Country[] = [
  { code: 'BRA', alpha2: 'BR', name: 'Brasil', phoneCode: '+55', flag: flag('BR') },
  { code: 'AFG', alpha2: 'AF', name: 'Afeganistão', phoneCode: '+93', flag: flag('AF') },
  { code: 'ZAF', alpha2: 'ZA', name: 'África do Sul', phoneCode: '+27', flag: flag('ZA') },
  { code: 'ALB', alpha2: 'AL', name: 'Albânia', phoneCode: '+355', flag: flag('AL') },
  { code: 'DEU', alpha2: 'DE', name: 'Alemanha', phoneCode: '+49', flag: flag('DE') },
  { code: 'AND', alpha2: 'AD', name: 'Andorra', phoneCode: '+376', flag: flag('AD') },
  { code: 'AGO', alpha2: 'AO', name: 'Angola', phoneCode: '+244', flag: flag('AO') },
  { code: 'ATG', alpha2: 'AG', name: 'Antígua e Barbuda', phoneCode: '+1', flag: flag('AG') },
  { code: 'SAU', alpha2: 'SA', name: 'Arábia Saudita', phoneCode: '+966', flag: flag('SA') },
  { code: 'DZA', alpha2: 'DZ', name: 'Argélia', phoneCode: '+213', flag: flag('DZ') },
  { code: 'ARG', alpha2: 'AR', name: 'Argentina', phoneCode: '+54', flag: flag('AR') },
  { code: 'ARM', alpha2: 'AM', name: 'Armênia', phoneCode: '+374', flag: flag('AM') },
  { code: 'AUS', alpha2: 'AU', name: 'Austrália', phoneCode: '+61', flag: flag('AU') },
  { code: 'AUT', alpha2: 'AT', name: 'Áustria', phoneCode: '+43', flag: flag('AT') },
  { code: 'AZE', alpha2: 'AZ', name: 'Azerbaijão', phoneCode: '+994', flag: flag('AZ') },
  { code: 'BHS', alpha2: 'BS', name: 'Bahamas', phoneCode: '+1', flag: flag('BS') },
  { code: 'BGD', alpha2: 'BD', name: 'Bangladesh', phoneCode: '+880', flag: flag('BD') },
  { code: 'BRB', alpha2: 'BB', name: 'Barbados', phoneCode: '+1', flag: flag('BB') },
  { code: 'BHR', alpha2: 'BH', name: 'Barein', phoneCode: '+973', flag: flag('BH') },
  { code: 'BLR', alpha2: 'BY', name: 'Belarus', phoneCode: '+375', flag: flag('BY') },
  { code: 'BEL', alpha2: 'BE', name: 'Bélgica', phoneCode: '+32', flag: flag('BE') },
  { code: 'BLZ', alpha2: 'BZ', name: 'Belize', phoneCode: '+501', flag: flag('BZ') },
  { code: 'BEN', alpha2: 'BJ', name: 'Benin', phoneCode: '+229', flag: flag('BJ') },
  { code: 'BOL', alpha2: 'BO', name: 'Bolívia', phoneCode: '+591', flag: flag('BO') },
  { code: 'BIH', alpha2: 'BA', name: 'Bósnia e Herzegovina', phoneCode: '+387', flag: flag('BA') },
  { code: 'BWA', alpha2: 'BW', name: 'Botsuana', phoneCode: '+267', flag: flag('BW') },
  { code: 'BRN', alpha2: 'BN', name: 'Brunei', phoneCode: '+673', flag: flag('BN') },
  { code: 'BGR', alpha2: 'BG', name: 'Bulgária', phoneCode: '+359', flag: flag('BG') },
  { code: 'BFA', alpha2: 'BF', name: 'Burkina Faso', phoneCode: '+226', flag: flag('BF') },
  { code: 'BDI', alpha2: 'BI', name: 'Burundi', phoneCode: '+257', flag: flag('BI') },
  { code: 'BTN', alpha2: 'BT', name: 'Butão', phoneCode: '+975', flag: flag('BT') },
  { code: 'CPV', alpha2: 'CV', name: 'Cabo Verde', phoneCode: '+238', flag: flag('CV') },
  { code: 'CMR', alpha2: 'CM', name: 'Camarões', phoneCode: '+237', flag: flag('CM') },
  { code: 'KHM', alpha2: 'KH', name: 'Camboja', phoneCode: '+855', flag: flag('KH') },
  { code: 'CAN', alpha2: 'CA', name: 'Canadá', phoneCode: '+1', flag: flag('CA') },
  { code: 'QAT', alpha2: 'QA', name: 'Catar', phoneCode: '+974', flag: flag('QA') },
  { code: 'KAZ', alpha2: 'KZ', name: 'Cazaquistão', phoneCode: '+7', flag: flag('KZ') },
  { code: 'TCD', alpha2: 'TD', name: 'Chade', phoneCode: '+235', flag: flag('TD') },
  { code: 'CHL', alpha2: 'CL', name: 'Chile', phoneCode: '+56', flag: flag('CL') },
  { code: 'CHN', alpha2: 'CN', name: 'China', phoneCode: '+86', flag: flag('CN') },
  { code: 'CYP', alpha2: 'CY', name: 'Chipre', phoneCode: '+357', flag: flag('CY') },
  { code: 'COL', alpha2: 'CO', name: 'Colômbia', phoneCode: '+57', flag: flag('CO') },
  { code: 'COM', alpha2: 'KM', name: 'Comores', phoneCode: '+269', flag: flag('KM') },
  { code: 'COG', alpha2: 'CG', name: 'Congo', phoneCode: '+242', flag: flag('CG') },
  { code: 'COD', alpha2: 'CD', name: 'Congo (RDC)', phoneCode: '+243', flag: flag('CD') },
  { code: 'PRK', alpha2: 'KP', name: 'Coreia do Norte', phoneCode: '+850', flag: flag('KP') },
  { code: 'KOR', alpha2: 'KR', name: 'Coreia do Sul', phoneCode: '+82', flag: flag('KR') },
  { code: 'CIV', alpha2: 'CI', name: 'Costa do Marfim', phoneCode: '+225', flag: flag('CI') },
  { code: 'CRI', alpha2: 'CR', name: 'Costa Rica', phoneCode: '+506', flag: flag('CR') },
  { code: 'HRV', alpha2: 'HR', name: 'Croácia', phoneCode: '+385', flag: flag('HR') },
  { code: 'CUB', alpha2: 'CU', name: 'Cuba', phoneCode: '+53', flag: flag('CU') },
  { code: 'DNK', alpha2: 'DK', name: 'Dinamarca', phoneCode: '+45', flag: flag('DK') },
  { code: 'DJI', alpha2: 'DJ', name: 'Djibuti', phoneCode: '+253', flag: flag('DJ') },
  { code: 'DMA', alpha2: 'DM', name: 'Dominica', phoneCode: '+1', flag: flag('DM') },
  { code: 'EGY', alpha2: 'EG', name: 'Egito', phoneCode: '+20', flag: flag('EG') },
  { code: 'SLV', alpha2: 'SV', name: 'El Salvador', phoneCode: '+503', flag: flag('SV') },
  { code: 'ARE', alpha2: 'AE', name: 'Emirados Árabes Unidos', phoneCode: '+971', flag: flag('AE') },
  { code: 'ECU', alpha2: 'EC', name: 'Equador', phoneCode: '+593', flag: flag('EC') },
  { code: 'ERI', alpha2: 'ER', name: 'Eritreia', phoneCode: '+291', flag: flag('ER') },
  { code: 'SVK', alpha2: 'SK', name: 'Eslováquia', phoneCode: '+421', flag: flag('SK') },
  { code: 'SVN', alpha2: 'SI', name: 'Eslovênia', phoneCode: '+386', flag: flag('SI') },
  { code: 'ESP', alpha2: 'ES', name: 'Espanha', phoneCode: '+34', flag: flag('ES') },
  { code: 'USA', alpha2: 'US', name: 'Estados Unidos', phoneCode: '+1', flag: flag('US') },
  { code: 'EST', alpha2: 'EE', name: 'Estônia', phoneCode: '+372', flag: flag('EE') },
  { code: 'SWZ', alpha2: 'SZ', name: 'Eswatini', phoneCode: '+268', flag: flag('SZ') },
  { code: 'ETH', alpha2: 'ET', name: 'Etiópia', phoneCode: '+251', flag: flag('ET') },
  { code: 'FJI', alpha2: 'FJ', name: 'Fiji', phoneCode: '+679', flag: flag('FJ') },
  { code: 'PHL', alpha2: 'PH', name: 'Filipinas', phoneCode: '+63', flag: flag('PH') },
  { code: 'FIN', alpha2: 'FI', name: 'Finlândia', phoneCode: '+358', flag: flag('FI') },
  { code: 'FRA', alpha2: 'FR', name: 'França', phoneCode: '+33', flag: flag('FR') },
  { code: 'GAB', alpha2: 'GA', name: 'Gabão', phoneCode: '+241', flag: flag('GA') },
  { code: 'GMB', alpha2: 'GM', name: 'Gâmbia', phoneCode: '+220', flag: flag('GM') },
  { code: 'GHA', alpha2: 'GH', name: 'Gana', phoneCode: '+233', flag: flag('GH') },
  { code: 'GEO', alpha2: 'GE', name: 'Geórgia', phoneCode: '+995', flag: flag('GE') },
  { code: 'GRD', alpha2: 'GD', name: 'Granada', phoneCode: '+1', flag: flag('GD') },
  { code: 'GRC', alpha2: 'GR', name: 'Grécia', phoneCode: '+30', flag: flag('GR') },
  { code: 'GTM', alpha2: 'GT', name: 'Guatemala', phoneCode: '+502', flag: flag('GT') },
  { code: 'GUY', alpha2: 'GY', name: 'Guiana', phoneCode: '+592', flag: flag('GY') },
  { code: 'GNB', alpha2: 'GW', name: 'Guiné-Bissau', phoneCode: '+245', flag: flag('GW') },
  { code: 'GIN', alpha2: 'GN', name: 'Guiné', phoneCode: '+224', flag: flag('GN') },
  { code: 'GNQ', alpha2: 'GQ', name: 'Guiné Equatorial', phoneCode: '+240', flag: flag('GQ') },
  { code: 'HTI', alpha2: 'HT', name: 'Haiti', phoneCode: '+509', flag: flag('HT') },
  { code: 'HND', alpha2: 'HN', name: 'Honduras', phoneCode: '+504', flag: flag('HN') },
  { code: 'HUN', alpha2: 'HU', name: 'Hungria', phoneCode: '+36', flag: flag('HU') },
  { code: 'YEM', alpha2: 'YE', name: 'Iêmen', phoneCode: '+967', flag: flag('YE') },
  { code: 'IND', alpha2: 'IN', name: 'Índia', phoneCode: '+91', flag: flag('IN') },
  { code: 'IDN', alpha2: 'ID', name: 'Indonésia', phoneCode: '+62', flag: flag('ID') },
  { code: 'IRQ', alpha2: 'IQ', name: 'Iraque', phoneCode: '+964', flag: flag('IQ') },
  { code: 'IRN', alpha2: 'IR', name: 'Irã', phoneCode: '+98', flag: flag('IR') },
  { code: 'IRL', alpha2: 'IE', name: 'Irlanda', phoneCode: '+353', flag: flag('IE') },
  { code: 'ISL', alpha2: 'IS', name: 'Islândia', phoneCode: '+354', flag: flag('IS') },
  { code: 'ISR', alpha2: 'IL', name: 'Israel', phoneCode: '+972', flag: flag('IL') },
  { code: 'ITA', alpha2: 'IT', name: 'Itália', phoneCode: '+39', flag: flag('IT') },
  { code: 'JAM', alpha2: 'JM', name: 'Jamaica', phoneCode: '+1', flag: flag('JM') },
  { code: 'JPN', alpha2: 'JP', name: 'Japão', phoneCode: '+81', flag: flag('JP') },
  { code: 'JOR', alpha2: 'JO', name: 'Jordânia', phoneCode: '+962', flag: flag('JO') },
  { code: 'KWT', alpha2: 'KW', name: 'Kuwait', phoneCode: '+965', flag: flag('KW') },
  { code: 'LAO', alpha2: 'LA', name: 'Laos', phoneCode: '+856', flag: flag('LA') },
  { code: 'LSO', alpha2: 'LS', name: 'Lesoto', phoneCode: '+266', flag: flag('LS') },
  { code: 'LVA', alpha2: 'LV', name: 'Letônia', phoneCode: '+371', flag: flag('LV') },
  { code: 'LBN', alpha2: 'LB', name: 'Líbano', phoneCode: '+961', flag: flag('LB') },
  { code: 'LBR', alpha2: 'LR', name: 'Libéria', phoneCode: '+231', flag: flag('LR') },
  { code: 'LBY', alpha2: 'LY', name: 'Líbia', phoneCode: '+218', flag: flag('LY') },
  { code: 'LIE', alpha2: 'LI', name: 'Liechtenstein', phoneCode: '+423', flag: flag('LI') },
  { code: 'LTU', alpha2: 'LT', name: 'Lituânia', phoneCode: '+370', flag: flag('LT') },
  { code: 'LUX', alpha2: 'LU', name: 'Luxemburgo', phoneCode: '+352', flag: flag('LU') },
  { code: 'MKD', alpha2: 'MK', name: 'Macedônia do Norte', phoneCode: '+389', flag: flag('MK') },
  { code: 'MDG', alpha2: 'MG', name: 'Madagascar', phoneCode: '+261', flag: flag('MG') },
  { code: 'MYS', alpha2: 'MY', name: 'Malásia', phoneCode: '+60', flag: flag('MY') },
  { code: 'MWI', alpha2: 'MW', name: 'Malaui', phoneCode: '+265', flag: flag('MW') },
  { code: 'MDV', alpha2: 'MV', name: 'Maldivas', phoneCode: '+960', flag: flag('MV') },
  { code: 'MLI', alpha2: 'ML', name: 'Mali', phoneCode: '+223', flag: flag('ML') },
  { code: 'MLT', alpha2: 'MT', name: 'Malta', phoneCode: '+356', flag: flag('MT') },
  { code: 'MAR', alpha2: 'MA', name: 'Marrocos', phoneCode: '+212', flag: flag('MA') },
  { code: 'MUS', alpha2: 'MU', name: 'Maurício', phoneCode: '+230', flag: flag('MU') },
  { code: 'MRT', alpha2: 'MR', name: 'Mauritânia', phoneCode: '+222', flag: flag('MR') },
  { code: 'MEX', alpha2: 'MX', name: 'México', phoneCode: '+52', flag: flag('MX') },
  { code: 'MMR', alpha2: 'MM', name: 'Mianmar', phoneCode: '+95', flag: flag('MM') },
  { code: 'FSM', alpha2: 'FM', name: 'Micronésia', phoneCode: '+691', flag: flag('FM') },
  { code: 'MOZ', alpha2: 'MZ', name: 'Moçambique', phoneCode: '+258', flag: flag('MZ') },
  { code: 'MDA', alpha2: 'MD', name: 'Moldávia', phoneCode: '+373', flag: flag('MD') },
  { code: 'MCO', alpha2: 'MC', name: 'Mônaco', phoneCode: '+377', flag: flag('MC') },
  { code: 'MNG', alpha2: 'MN', name: 'Mongólia', phoneCode: '+976', flag: flag('MN') },
  { code: 'MNE', alpha2: 'ME', name: 'Montenegro', phoneCode: '+382', flag: flag('ME') },
  { code: 'NAM', alpha2: 'NA', name: 'Namíbia', phoneCode: '+264', flag: flag('NA') },
  { code: 'NRU', alpha2: 'NR', name: 'Nauru', phoneCode: '+674', flag: flag('NR') },
  { code: 'NPL', alpha2: 'NP', name: 'Nepal', phoneCode: '+977', flag: flag('NP') },
  { code: 'NIC', alpha2: 'NI', name: 'Nicarágua', phoneCode: '+505', flag: flag('NI') },
  { code: 'NER', alpha2: 'NE', name: 'Níger', phoneCode: '+227', flag: flag('NE') },
  { code: 'NGA', alpha2: 'NG', name: 'Nigéria', phoneCode: '+234', flag: flag('NG') },
  { code: 'NOR', alpha2: 'NO', name: 'Noruega', phoneCode: '+47', flag: flag('NO') },
  { code: 'NZL', alpha2: 'NZ', name: 'Nova Zelândia', phoneCode: '+64', flag: flag('NZ') },
  { code: 'OMN', alpha2: 'OM', name: 'Omã', phoneCode: '+968', flag: flag('OM') },
  { code: 'NLD', alpha2: 'NL', name: 'Países Baixos', phoneCode: '+31', flag: flag('NL') },
  { code: 'PLW', alpha2: 'PW', name: 'Palau', phoneCode: '+680', flag: flag('PW') },
  { code: 'PAN', alpha2: 'PA', name: 'Panamá', phoneCode: '+507', flag: flag('PA') },
  { code: 'PNG', alpha2: 'PG', name: 'Papua-Nova Guiné', phoneCode: '+675', flag: flag('PG') },
  { code: 'PAK', alpha2: 'PK', name: 'Paquistão', phoneCode: '+92', flag: flag('PK') },
  { code: 'PRY', alpha2: 'PY', name: 'Paraguai', phoneCode: '+595', flag: flag('PY') },
  { code: 'PER', alpha2: 'PE', name: 'Peru', phoneCode: '+51', flag: flag('PE') },
  { code: 'POL', alpha2: 'PL', name: 'Polônia', phoneCode: '+48', flag: flag('PL') },
  { code: 'PRT', alpha2: 'PT', name: 'Portugal', phoneCode: '+351', flag: flag('PT') },
  { code: 'KEN', alpha2: 'KE', name: 'Quênia', phoneCode: '+254', flag: flag('KE') },
  { code: 'KGZ', alpha2: 'KG', name: 'Quirguistão', phoneCode: '+996', flag: flag('KG') },
  { code: 'GBR', alpha2: 'GB', name: 'Reino Unido', phoneCode: '+44', flag: flag('GB') },
  { code: 'CAF', alpha2: 'CF', name: 'República Centro-Africana', phoneCode: '+236', flag: flag('CF') },
  { code: 'DOM', alpha2: 'DO', name: 'República Dominicana', phoneCode: '+1', flag: flag('DO') },
  { code: 'CZE', alpha2: 'CZ', name: 'República Tcheca', phoneCode: '+420', flag: flag('CZ') },
  { code: 'ROU', alpha2: 'RO', name: 'Romênia', phoneCode: '+40', flag: flag('RO') },
  { code: 'RWA', alpha2: 'RW', name: 'Ruanda', phoneCode: '+250', flag: flag('RW') },
  { code: 'RUS', alpha2: 'RU', name: 'Rússia', phoneCode: '+7', flag: flag('RU') },
  { code: 'WSM', alpha2: 'WS', name: 'Samoa', phoneCode: '+685', flag: flag('WS') },
  { code: 'SMR', alpha2: 'SM', name: 'San Marino', phoneCode: '+378', flag: flag('SM') },
  { code: 'LCA', alpha2: 'LC', name: 'Santa Lúcia', phoneCode: '+1', flag: flag('LC') },
  { code: 'KNA', alpha2: 'KN', name: 'São Cristóvão e Névis', phoneCode: '+1', flag: flag('KN') },
  { code: 'STP', alpha2: 'ST', name: 'São Tomé e Príncipe', phoneCode: '+239', flag: flag('ST') },
  { code: 'VCT', alpha2: 'VC', name: 'São Vicente e Granadinas', phoneCode: '+1', flag: flag('VC') },
  { code: 'SEN', alpha2: 'SN', name: 'Senegal', phoneCode: '+221', flag: flag('SN') },
  { code: 'SLE', alpha2: 'SL', name: 'Serra Leoa', phoneCode: '+232', flag: flag('SL') },
  { code: 'SRB', alpha2: 'RS', name: 'Sérvia', phoneCode: '+381', flag: flag('RS') },
  { code: 'SYC', alpha2: 'SC', name: 'Seychelles', phoneCode: '+248', flag: flag('SC') },
  { code: 'SGP', alpha2: 'SG', name: 'Singapura', phoneCode: '+65', flag: flag('SG') },
  { code: 'SYR', alpha2: 'SY', name: 'Síria', phoneCode: '+963', flag: flag('SY') },
  { code: 'SOM', alpha2: 'SO', name: 'Somália', phoneCode: '+252', flag: flag('SO') },
  { code: 'LKA', alpha2: 'LK', name: 'Sri Lanka', phoneCode: '+94', flag: flag('LK') },
  { code: 'SDN', alpha2: 'SD', name: 'Sudão', phoneCode: '+249', flag: flag('SD') },
  { code: 'SSD', alpha2: 'SS', name: 'Sudão do Sul', phoneCode: '+211', flag: flag('SS') },
  { code: 'SWE', alpha2: 'SE', name: 'Suécia', phoneCode: '+46', flag: flag('SE') },
  { code: 'CHE', alpha2: 'CH', name: 'Suíça', phoneCode: '+41', flag: flag('CH') },
  { code: 'SUR', alpha2: 'SR', name: 'Suriname', phoneCode: '+597', flag: flag('SR') },
  { code: 'TJK', alpha2: 'TJ', name: 'Tajiquistão', phoneCode: '+992', flag: flag('TJ') },
  { code: 'THA', alpha2: 'TH', name: 'Tailândia', phoneCode: '+66', flag: flag('TH') },
  { code: 'TWN', alpha2: 'TW', name: 'Taiwan', phoneCode: '+886', flag: flag('TW') },
  { code: 'TZA', alpha2: 'TZ', name: 'Tanzânia', phoneCode: '+255', flag: flag('TZ') },
  { code: 'TLS', alpha2: 'TL', name: 'Timor-Leste', phoneCode: '+670', flag: flag('TL') },
  { code: 'TGO', alpha2: 'TG', name: 'Togo', phoneCode: '+228', flag: flag('TG') },
  { code: 'TON', alpha2: 'TO', name: 'Tonga', phoneCode: '+676', flag: flag('TO') },
  { code: 'TTO', alpha2: 'TT', name: 'Trinidad e Tobago', phoneCode: '+1', flag: flag('TT') },
  { code: 'TUN', alpha2: 'TN', name: 'Tunísia', phoneCode: '+216', flag: flag('TN') },
  { code: 'TKM', alpha2: 'TM', name: 'Turcomenistão', phoneCode: '+993', flag: flag('TM') },
  { code: 'TUR', alpha2: 'TR', name: 'Turquia', phoneCode: '+90', flag: flag('TR') },
  { code: 'TUV', alpha2: 'TV', name: 'Tuvalu', phoneCode: '+688', flag: flag('TV') },
  { code: 'UKR', alpha2: 'UA', name: 'Ucrânia', phoneCode: '+380', flag: flag('UA') },
  { code: 'UGA', alpha2: 'UG', name: 'Uganda', phoneCode: '+256', flag: flag('UG') },
  { code: 'URY', alpha2: 'UY', name: 'Uruguai', phoneCode: '+598', flag: flag('UY') },
  { code: 'UZB', alpha2: 'UZ', name: 'Uzbequistão', phoneCode: '+998', flag: flag('UZ') },
  { code: 'VUT', alpha2: 'VU', name: 'Vanuatu', phoneCode: '+678', flag: flag('VU') },
  { code: 'VAT', alpha2: 'VA', name: 'Vaticano', phoneCode: '+379', flag: flag('VA') },
  { code: 'VEN', alpha2: 'VE', name: 'Venezuela', phoneCode: '+58', flag: flag('VE') },
  { code: 'VNM', alpha2: 'VN', name: 'Vietnã', phoneCode: '+84', flag: flag('VN') },
  { code: 'ZMB', alpha2: 'ZM', name: 'Zâmbia', phoneCode: '+260', flag: flag('ZM') },
  { code: 'ZWE', alpha2: 'ZW', name: 'Zimbábue', phoneCode: '+263', flag: flag('ZW') },
];

/** Common phone country codes for the phone input dropdown */
export const COMMON_PHONE_COUNTRIES = [
  'BR', 'US', 'PT', 'AR', 'CO', 'VE', 'BO', 'PY', 'UY', 'PE',
  'CL', 'MX', 'ES', 'FR', 'DE', 'IT', 'GB', 'JP',
];
